# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    parameter_name: value

services:
    feature_toggles:
        class: App\Common\Services\FeatureTogglesService
        arguments: [@doctrine.orm.entity_manager]



