<?php

namespace App\FeatureTogglesBundle\Repository;

/**
 * FeatureFlagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeatureFlagRepository extends \Doctrine\ORM\EntityRepository
{
}
